const WeatherIcons = [

{
    "id": 1,
    "path": "/img/weather_icon-01.png"
}, {
    "id": 2,
    "path": "/img/weather_icon-02.png"
}, {
    "id": 3,
    "path": "/img/weather_icon-03.png"
}, {
    "id": 4,
    "path": "/img/weather_icon-04.png"
}, {
    "id": 5,
    "path": "/img/weather_icon-05.png"
}, {
    "id": 6,
    "path": "/img/weather_icon-06.png"
}, {
    "id": 7,
    "path": "/img/weather_icon-07.png"
}, {
    "id": 8,
    "path": "/img/weather_icon-08.png"
}, {
    "id": 9,
    "path": "/img/weather_icon-09.png"
}, {
    "id": 10,
    "path": "/img/weather_icon-10.png"
}, {
    "id": 11,
    "path": "/img/weather_icon-11.png"
}, {
    "id": 12,
    "path": "/img/weather_icon-12.png"
}, {
    "id": 13,
    "path": "/img/weather_icon-13.png"
}, {
    "id": 14,
    "path": "/img/weather_icon-14.png"
}, {
    "id": 15,
    "path": "/img/weather_icon-15.png"
}, {
    "id": 16,
    "path": "/img/weather_icon-16.png"
}, {
    "id": 17,
    "path": "/img/weather_icon-17.png"
}, {
    "id": 18,
    "path": "/img/weather_icon-18.png"
}, {
    "id": 19,
    "path": "/img/weather_icon-19.png"
}, {
    "id": 20,
    "path": "/img/weather_icon-20.png"
}, {
    "id": 21,
    "path": "/img/weather_icon-21.png"
}, {
    "id": 22,
    "path": "/img/weather_icon-22.png"
}, {
    "id": 23,
    "path": "/img/weather_icon-23.png"
}, {
    "id": 24,
    "path": "/img/weather_icon-24.png"
}, {
    "id": 25,
    "path": "/img/weather_icon-25.png"
}, {
    "id": 26,
    "path": "/img/weather_icon-26.png"
}, {
    "id": 27,
    "path": "/img/weather_icon-27.png"
}, {
    "id": 28,
    "path": "/img/weather_icon-28.png"
}, {
    "id": 29,
    "path": "/img/weather_icon-29.png"
}, {
    "id": 30,
    "path": "/img/weather_icon-30.png"
}, {
    "id": 31,
    "path": "/img/weather_icon-31.png"
}, {
    "id": 32,
    "path": "/img/weather_icon-32.png"
}, {
    "id": 33,
    "path": "/img/weather_icon-33.png"
}, {
    "id": 34,
    "path": "/img/weather_icon-34.png"
}, {
    "id": 35,
    "path": "/img/weather_icon-35.png"
}, {
    "id": 36,
    "path": "/img/weather_icon-36.png"
}, {
    "id": 37,
    "path": "/img/weather_icon-37.png"
}, {
    "id": 38,
    "path": "/img/weather_icon-38.png"
}, {
    "id": 39,
    "path": "/img/weather_icon-39.png"
}, {
    "id": 40,
    "path": "/img/weather_icon-40.png"
}, {
    "id": 41,
    "path": "/img/weather_icon-41.png"
}, {
    "id": 42,
    "path": "/img/weather_icon-42.png"
}, {
    "id": 43,
    "path": "/img/weather_icon-43.png"
}, {
    "id": 44,
    "path": "/img/weather_icon-44.png"
}, {
    "id": 45,
    "path": "/img/weather_icon-45.png"
}, {
    "id": 46,
    "path": "/img/weather_icon-46.png"
}, {
    "id": 47,
    "path": "/img/weather_icon-47.png"
}, {
    "id": 48,
    "path": "/img/weather_icon-48.png"
}, {
    "id": 49,
    "path": "/img/weather_icon-49.png"
}, {
    "id": 50,
    "path": "/img/weather_icon-50.png"
}, {
    "id": 51,
    "path": "/img/weather_icon-51.png"
}, {
    "id": 52,
    "path": "/img/weather_icon-52.png"
}, {
    "id": 53,
    "path": "/img/weather_icon-53.png"
}, {
    "id": 54,
    "path": "/img/weather_icon-54.png"
}, {
    "id": 55,
    "path": "/img/weather_icon-55.png"
}, {
    "id": 56,
    "path": "/img/weather_icon-56.png"
}, {
    "id": 57,
    "path": "/img/weather_icon-57.png"
}, {
    "id": 58,
    "path": "/img/weather_icon-58.png"
}, {
    "id": 59,
    "path": "/img/weather_icon-59.png"
}, {
    "id": 60,
    "path": "/img/weather_icon-60.png"
}, {
    "id": 61,
    "path": "/img/weather_icon-61.png"
}, {
    "id": 62,
    "path": "/img/weather_icon-62.png"
}, {
    "id": 63,
    "path": "/img/weather_icon-63.png"
}, {
    "id": 64,
    "path": "/img/weather_icon-64.png"
}, {
    "id": 65,
    "path": "/img/weather_icon-65.png"
}, {
    "id": 66,
    "path": "/img/weather_icon-66.png"
}, {
    "id": 67,
    "path": "/img/weather_icon-67.png"
}, {
    "id": 68,
    "path": "/img/weather_icon-68.png"
}, {
    "id": 69,
    "path": "/img/weather_icon-69.png"
}, {
    "id": 70,
    "path": "/img/weather_icon-70.png"
}

]